development:
  adapter: postgresql
  database: lanadelrey_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  database: lanadelrey_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  database: lanadelrey_production
  pool: 5
  username: postgres
  password:
